### ISSUE TITLE
Organise Tournament form

### ISSUE THREAD

**Issue by ukanishk** [michaelmulianto/SEG-Team-Chickaree#118] opened 2021-12-10 16:57 UTC
The organise tournament form does not get submitted when you enter incorrect values but it displays “Looks good” as the message. I think we need some kind of form validation with new messages.

**Comment by kieranw-8** [comment] 2021-12-11 18:01
On my local machine only the valid fields get the "Looks good" message. Can someone else check?

**Comment by lclarkg18** [comment] 2021-12-13 01:14
Duplicate of Issue 133

**Closed by lclarkg18** 2021-12-13 01:14 UTC
Labels: bug, duplicate
